/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_helloface_HelloFaceActivity */

#ifndef _Included_edu_stanford_helloface_HelloFaceActivity
#define _Included_edu_stanford_helloface_HelloFaceActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_stanford_helloface_HelloFaceActivity_BIND_ABOVE_CLIENT
#define edu_stanford_helloface_HelloFaceActivity_BIND_ABOVE_CLIENT 8L
#undef edu_stanford_helloface_HelloFaceActivity_BIND_ADJUST_WITH_ACTIVITY
#define edu_stanford_helloface_HelloFaceActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef edu_stanford_helloface_HelloFaceActivity_BIND_ALLOW_OOM_MANAGEMENT
#define edu_stanford_helloface_HelloFaceActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef edu_stanford_helloface_HelloFaceActivity_BIND_AUTO_CREATE
#define edu_stanford_helloface_HelloFaceActivity_BIND_AUTO_CREATE 1L
#undef edu_stanford_helloface_HelloFaceActivity_BIND_DEBUG_UNBIND
#define edu_stanford_helloface_HelloFaceActivity_BIND_DEBUG_UNBIND 2L
#undef edu_stanford_helloface_HelloFaceActivity_BIND_IMPORTANT
#define edu_stanford_helloface_HelloFaceActivity_BIND_IMPORTANT 64L
#undef edu_stanford_helloface_HelloFaceActivity_BIND_NOT_FOREGROUND
#define edu_stanford_helloface_HelloFaceActivity_BIND_NOT_FOREGROUND 4L
#undef edu_stanford_helloface_HelloFaceActivity_BIND_WAIVE_PRIORITY
#define edu_stanford_helloface_HelloFaceActivity_BIND_WAIVE_PRIORITY 32L
#undef edu_stanford_helloface_HelloFaceActivity_CONTEXT_IGNORE_SECURITY
#define edu_stanford_helloface_HelloFaceActivity_CONTEXT_IGNORE_SECURITY 2L
#undef edu_stanford_helloface_HelloFaceActivity_CONTEXT_INCLUDE_CODE
#define edu_stanford_helloface_HelloFaceActivity_CONTEXT_INCLUDE_CODE 1L
#undef edu_stanford_helloface_HelloFaceActivity_CONTEXT_RESTRICTED
#define edu_stanford_helloface_HelloFaceActivity_CONTEXT_RESTRICTED 4L
#undef edu_stanford_helloface_HelloFaceActivity_MODE_APPEND
#define edu_stanford_helloface_HelloFaceActivity_MODE_APPEND 32768L
#undef edu_stanford_helloface_HelloFaceActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define edu_stanford_helloface_HelloFaceActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef edu_stanford_helloface_HelloFaceActivity_MODE_MULTI_PROCESS
#define edu_stanford_helloface_HelloFaceActivity_MODE_MULTI_PROCESS 4L
#undef edu_stanford_helloface_HelloFaceActivity_MODE_PRIVATE
#define edu_stanford_helloface_HelloFaceActivity_MODE_PRIVATE 0L
#undef edu_stanford_helloface_HelloFaceActivity_MODE_WORLD_READABLE
#define edu_stanford_helloface_HelloFaceActivity_MODE_WORLD_READABLE 1L
#undef edu_stanford_helloface_HelloFaceActivity_MODE_WORLD_WRITEABLE
#define edu_stanford_helloface_HelloFaceActivity_MODE_WORLD_WRITEABLE 2L
#undef edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_DIALER
#define edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_DIALER 1L
#undef edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_DISABLE
#define edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_DISABLE 0L
#undef edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_SHORTCUT
#define edu_stanford_helloface_HelloFaceActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef edu_stanford_helloface_HelloFaceActivity_RESULT_CANCELED
#define edu_stanford_helloface_HelloFaceActivity_RESULT_CANCELED 0L
#undef edu_stanford_helloface_HelloFaceActivity_RESULT_FIRST_USER
#define edu_stanford_helloface_HelloFaceActivity_RESULT_FIRST_USER 1L
#undef edu_stanford_helloface_HelloFaceActivity_RESULT_OK
#define edu_stanford_helloface_HelloFaceActivity_RESULT_OK -1L
/*
 * Class:     edu_stanford_helloface_HelloFaceActivity
 * Method:    CreateNativeController
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_stanford_helloface_HelloFaceActivity_CreateNativeController
  (JNIEnv *, jobject);

/*
 * Class:     edu_stanford_helloface_HelloFaceActivity
 * Method:    DestroyNativeController
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_stanford_helloface_HelloFaceActivity_DestroyNativeController
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_stanford_helloface_HelloFaceActivity
 * Method:    HandleFrame
 * Signature: (JJZZ[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_edu_stanford_helloface_HelloFaceActivity_HandleFrame
  (JNIEnv *, jobject, jlong, jlong, jboolean, jboolean, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
